// <auto-generated />
using System;
using AutoPartsStore.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AutoPartsStore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210801220222_AddingAttributes")]
    partial class AddingAttributes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AutoPartsStore.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Brakes"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Engine"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Suspension"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Exhaust"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Air Conditioning"
                        });
                });

            modelBuilder.Entity("AutoPartsStore.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("OrderPlaced")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("OrderTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("AutoPartsStore.Models.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("PartId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("OrderId");

                    b.HasIndex("PartId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("AutoPartsStore.Models.Part", b =>
                {
                    b.Property<int>("PartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsInStock")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOnSale")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PartId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Parts");

                    b.HasData(
                        new
                        {
                            PartId = 1,
                            CategoryId = 1,
                            Description = "Z16 Evolution Ceramic brake pads are the affordable stock replacement for your daily driven vehicle. The low dust Ceramic formula is validated through on-vehicle 3rd party tests in the USA to keep your wheels looking like new.",
                            ImageThumbnailUrl = "\\Images\\thumbnails\\16-537__ra_p-small.jpg",
                            ImageUrl = "\\Images\\16-537__ra_p.jpg",
                            IsInStock = true,
                            IsOnSale = false,
                            Name = "POWER STOP 16537 Z16",
                            Price = 18.22m
                        },
                        new
                        {
                            PartId = 2,
                            CategoryId = 1,
                            Description = "Wagner® E-Coat Brake rotors are engineered for maximum performance with an E-Shield® protective electro-coating applied to all non-braking surfaces. This black-colored coating prevents corrosion, makes removal for service fast and simple, and is visually attractive for open spoke wheels.",
                            ImageThumbnailUrl = "\\Images\\thumbnails\\MWG_BD126055E_P04_ANG__ra_p-small.jpg",
                            ImageUrl = "\\Images\\MWG_BD126055E_P04_ANG__ra_p.jpg",
                            IsInStock = true,
                            IsOnSale = false,
                            Name = "WAGNER BD126055E Black",
                            Price = 32.79m
                        },
                        new
                        {
                            PartId = 3,
                            CategoryId = 1,
                            Description = "ACDelco Gold (Professional) Remanufactured Coated Brake Calipers feature a robotic-applied, baked-on zinc plated coating that provides superior rust prevention against harsh environmental elements such as rain, snow, and corrosive road sprays.",
                            ImageThumbnailUrl = "\\Images\\thumbnails\\18FR2479C_Primary__ra_p-small.jpg",
                            ImageUrl = "\\Images\\18FR2479C_Primary__ra_p.jpg",
                            IsInStock = true,
                            IsOnSale = true,
                            Name = "ACDELCO 18FR2479C Gold",
                            Price = 137.79m
                        },
                        new
                        {
                            PartId = 4,
                            CategoryId = 2,
                            Description = "Beck/Arnley parts meet foreign nameplate OE specifications for form, fit and function. Their product specialists work with a network of global sourcing partners so you can install the right part with confidence.",
                            ImageThumbnailUrl = "\\Images\\thumbnails\\BA1041999-1__ra_p-small.jpg",
                            ImageUrl = "\\Images\\BA1041999-1__ra_p.jpg",
                            IsInStock = true,
                            IsOnSale = false,
                            Name = "BECK/ARNLEY 1041999",
                            Price = 60.79m
                        },
                        new
                        {
                            PartId = 5,
                            CategoryId = 2,
                            Description = "Melling is a leader in engineering design, development, prototype, testing and assembly of fluid delivery products and related items for the automotive OEM industry as well as the aftermarket industry.",
                            ImageThumbnailUrl = "\\Images\\thumbnails\\3-1035S-1-KIT__ra_p-small.jpg",
                            ImageUrl = "\\Images\\3-1035S-1-KIT__ra_p.jpg",
                            IsInStock = true,
                            IsOnSale = true,
                            Name = "MELLING 31035S",
                            Price = 125.79m
                        },
                        new
                        {
                            PartId = 6,
                            CategoryId = 2,
                            Description = "Melling is a leader in engineering design, development, prototype, testing and assembly of fluid delivery products and related items for the automotive OEM industry as well as the aftermarket industry.",
                            ImageThumbnailUrl = "\\Images\\thumbnails\\M532-1-FRO__ra_p-small.jpg",
                            ImageUrl = "\\Images\\M532-1-FRO__ra_p.jpg",
                            IsInStock = true,
                            IsOnSale = false,
                            Name = "MELLING M532",
                            Price = 180.79m
                        },
                        new
                        {
                            PartId = 7,
                            CategoryId = 3,
                            Description = "MOOG® products incorporate proven design and engineering features for like new steering, ease of installation and longer life. MOOG is the preferred steering and suspension brand of professional technicians and NASCAR crew chiefs.",
                            ImageThumbnailUrl = "\\Images\\thumbnails\\AMG_K500069_P04_ANG__ra_p-small.jpg",
                            ImageUrl = "\\Images\\AMG_K500069_P04_ANG__ra_p.jpg",
                            IsInStock = true,
                            IsOnSale = false,
                            Name = "MOOG K500069",
                            Price = 28.99m
                        },
                        new
                        {
                            PartId = 8,
                            CategoryId = 3,
                            Description = "The ACDelco Professional Suspension Stabilizer Bar Link Kit comes with everything you need to easily install new suspension stabilizer bar links, and is a high quality replacement for many vehicles on the road today.",
                            ImageThumbnailUrl = "\\Images\\thumbnails\\45G0452_Primary__ra_p-small.jpg",
                            ImageUrl = "\\Images\\45G0452_Primary__ra_p.jpg",
                            IsInStock = true,
                            IsOnSale = false,
                            Name = "ACDELCO 45G0452",
                            Price = 19.99m
                        },
                        new
                        {
                            PartId = 9,
                            CategoryId = 3,
                            Description = "Precisely calibrated to meet the OE design, each application-specific coil spring type is engineered to restore ride height and support the vehicle’s weight. Protective coating resists rust and corrosion while salt spray testing ensures it’s ready for the elements",
                            ImageThumbnailUrl = "\\Images\\thumbnails\\172287__ra_p-small.jpg",
                            ImageUrl = "\\Images\\172287__ra_p.jpg",
                            IsInStock = true,
                            IsOnSale = false,
                            Name = "MONROE 172286",
                            Price = 110.99m
                        },
                        new
                        {
                            PartId = 10,
                            CategoryId = 4,
                            Description = "Walker Ultra® Catalytic Converters are design-validated for assured fit, and provide EPA-compliant performance. Premium substrate material and a high-technology washcoat ensure exceptional oxygen storage capacity while OE expertise.",
                            ImageThumbnailUrl = "\\Images\\thumbnails\\BDCN_16448_P04_FRO__ra_p-small.jpg",
                            ImageUrl = "\\Images\\BDCN_16448_P04_FRO__ra_p.jpg",
                            IsInStock = true,
                            IsOnSale = true,
                            Name = "WALKER 16448 Ultra",
                            Price = 540.79m
                        },
                        new
                        {
                            PartId = 11,
                            CategoryId = 4,
                            Description = "Delphi exhaust gas recirculation (EGR) valves are a 100 percent OE line, providing an exact fit without the need for orifice washers or clocking for fast, easy installation.",
                            ImageThumbnailUrl = "\\Images\\thumbnails\\EG10499K__ra_p-small.jpg",
                            ImageUrl = "\\Images\\EG10499K__ra_p.jpg",
                            IsInStock = true,
                            IsOnSale = false,
                            Name = "DELPHI EG10499",
                            Price = 85.79m
                        },
                        new
                        {
                            PartId = 12,
                            CategoryId = 4,
                            Description = "Walker Quiet-Flow Mufflers feature 100% Structural Stainless Steel construction to resist rust-out three times longer than competitors' premium aluminized mufflers.",
                            ImageThumbnailUrl = "\\Images\\thumbnails\\BDCN_54668_P04_FRO__ra_p-small.jpg",
                            ImageUrl = "\\Images\\BDCN_54668_P04_FRO__ra_p.jpg",
                            IsInStock = true,
                            IsOnSale = false,
                            Name = "WALKER 54668",
                            Price = 92.89m
                        },
                        new
                        {
                            PartId = 13,
                            CategoryId = 5,
                            Description = "Manufactured and tested to the strictest OE standards for unparalleled performance. OE - specified O - rings & seals are compatible with both R12 and R134a refrigerants",
                            ImageThumbnailUrl = "\\Images\\thumbnails\\471-7054__ra_p-small.jpg",
                            ImageUrl = "\\Images\\471-7054__ra_p.jpg",
                            IsInStock = true,
                            IsOnSale = true,
                            Name = "DENSO 4717054",
                            Price = 259.99m
                        },
                        new
                        {
                            PartId = 14,
                            CategoryId = 5,
                            Description = "Old Refrigerant must be removed from the system in accordance with local, state, and federal laws. Replace the A / C Line O - Rings connected to the A / C Condenser to prevent a Refrigerant leak.",
                            ImageThumbnailUrl = "\\Images\\thumbnails\\10484_1_wm__ra_p-small.jpg",
                            ImageUrl = "\\Images\\10484_1_wm__ra_p.jpg",
                            IsInStock = true,
                            IsOnSale = false,
                            Name = "CSF 10484",
                            Price = 61.79m
                        },
                        new
                        {
                            PartId = 15,
                            CategoryId = 5,
                            Description = "Accumulators and receiver driers play an important part in the automotive air conditioning system. They are designed to hold a little extra refrigerant for hot days as well as having desiccant inside.",
                            ImageThumbnailUrl = "\\Images\\thumbnails\\1411667-1__ra_p-small.jpg",
                            ImageUrl = "\\Images\\1411667-1__ra_p.jpg",
                            IsInStock = true,
                            IsOnSale = false,
                            Name = "GPD 1411667",
                            Price = 10.17m
                        });
                });

            modelBuilder.Entity("AutoPartsStore.Models.ShoppingCartItem", b =>
                {
                    b.Property<int>("ShoppingCartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int?>("PartId")
                        .HasColumnType("int");

                    b.Property<string>("ShoppingCartId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ShoppingCartItemId");

                    b.HasIndex("PartId");

                    b.ToTable("ShoppingCartItems");
                });

            modelBuilder.Entity("AutoPartsStore.Models.OrderDetail", b =>
                {
                    b.HasOne("AutoPartsStore.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoPartsStore.Models.Part", "Part")
                        .WithMany()
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Part");
                });

            modelBuilder.Entity("AutoPartsStore.Models.Part", b =>
                {
                    b.HasOne("AutoPartsStore.Models.Category", "Category")
                        .WithMany("Parts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("AutoPartsStore.Models.ShoppingCartItem", b =>
                {
                    b.HasOne("AutoPartsStore.Models.Part", "Part")
                        .WithMany()
                        .HasForeignKey("PartId");

                    b.Navigation("Part");
                });

            modelBuilder.Entity("AutoPartsStore.Models.Category", b =>
                {
                    b.Navigation("Parts");
                });

            modelBuilder.Entity("AutoPartsStore.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
